# Generated by Django 4.2.4 on 2025-04-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='Rios', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=('Juan', 'Rios'), max_length=100),
            preserve_default=False,
        ),
    ]
