# Generated by Django 4.2.4 on 2025-03-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hora', 'Por Hora'), ('mensual', 'Mensual')], max_length=10)),
                ('vehiculo_tipo', models.CharField(choices=[('automovil', 'Automóvil'), ('moto', 'Moto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tarifa',
            },
        ),
    ]
